### PR TITLE
Made necessary changes to require display name

### PR DESCRIPTION
**Pull request by jhorwit2**
This is going to allow us to have better debugging, so lets require it.

### CODE REVIEW

**Comment by mako-taco** [comment]
Need to update tests as well so they dont throw errors.

**Comment by jhorwit2** [comment]
Well, that's weird. all my tests are passing locally.

**Comment by jhorwit2** [comment]
Just thought of something, I should also add a check to ensure that all displayNames are unique across Stores & ActionCreators. This will help with debugging.

**Comment by jhorwit2** [comment]
I'm also adding support for unique action sources. All this will help with debugging.

**Comment by jhorwit2** [comment]
To avoid merge conflicts I opted to fix #16 in this PR. We were missing the regex check for when required props were not passed to an action creator.

**Pull request merged**
