### PR TITLE
Don't trigger failure reactions for non-failure events

### PR DESCRIPTION
**Pull request by jeremybini**
This PR updates the `APIActionCreator` so that unintended actions/side-effects are not triggered when requests complete.

Previously, there were a couple of spots where mismatched actions or callbacks were being triggered:
- `handleFailure` could be called during success or abort actions, if the corresponding callbacks were not specified (ie: a success action without a handleSuccess, abort action without a handleAbort)
- The failure action could get dispatched when calling abort without a corresponding abort action

Test cases have been added to cover these scenarios, and the `send` callback has been updated.

### CODE REVIEW

**Review by jmrog — APPROVED** [review]
LGTM, thanks!

**Comment by jeremybini** [comment]
Thanks for getting this in! Any idea when you might be able to get a new release cut for this?

**Comment by dmvjs** [comment]
https://github.com/addthis/fluxthis/releases/tag/3.1.2

**Comment by jeremybini** [comment]
Great, thank you!

**Comment by jeremybini** [comment]
Hey there, just a heads up - I'm not seeing the most recent release in npm. It's still listing 3.1.1 as the latest

**Comment by dmvjs** [comment]
Thanks, hopefully this gets resolved today and will be published soon. Ill update here once it’s ready.


Kirk Elliott | Principal Software Engineer 
Cell +1.202.733.0317
Oracle Data Cloud

**Comment by dmvjs** [comment]
should be good to go 3.1.2 https://www.npmjs.com/package/fluxthis

**Pull request merged**
