### PR TITLE
Fixed bind actions bug. Renamed files for easier requiring

### PR DESCRIPTION
**Pull request by jhorwit2**
Fixed an issue when `init` didn't call `this.bindActions`. The result was that the store wasn't setup properly and didn't have a dispatch token among w/e else was missing in that method to setup the store (like test utils). 

Also, I renamed the files from es6.js to .js since most people don't have es6.js as a require. Plus our docs say to `require('fluxthis/src/ImmutableStore')`, which will fail for everyone since 99% of people probably don't have `es6.js` as a require extension. 

I added a test for `this.bindActions`. Once this PR is merged, we should publish.

### CODE REVIEW

**Comment by mako-taco** [comment]
I dont agree with the .es6.js changes.  people shouldn't blindly load vanilla thorugh an es6 loader; it will make their builds crawl....

**Comment by jhorwit2** [comment]
We shouldnt require people to use webpack. Its also not common at all to use es6.js from my experience. Also it wont make their builds crawl. Even on site its negligible to add all our js files instead of select ones.. Babel themselves dont even use es6.js :).

An example use case is that i have a store that has hard coded data since we havent moved towards dynamically generating content. Once we move towards generating content ill add actions and such to receive data. This is for the templates in custom messages. Eventually we want to do way more fancy stuff but for now it makes sense just to make a store to handle this that way when we move to dyanmic data all you need to update is the store and not any controller views.

**Comment by jhorwit2** [comment]
Also, we explictly say everywhere in the docs you need an es6 loader to require source files individually. That alleviates confusion requiring es6 js bc we make note everywhere it says to require the src file.

**Comment by jhorwit2** [comment]
Btw, the only performance optimization loaders like babel say to use for speed boost is ignore node modules. In such a case, we should provide a regex to include our lib.

https://github.com/babel/babel-loader/issues/4

**Comment by jhorwit2** [comment]
If you really want to keep es6.js, then lets update the docs and ill revert that change.

**Comment by jhorwit2** [comment]
Oh yea, another crappy thing about the es6.js is i cant use our package with babel-node :(. I was trying to run tests on a new feature and couldnt :(.

**Pull request merged**
