### PR TITLE
Cut new release for v3.1.1

### PR DESCRIPTION
**Pull request by rjmcneill**
With the bug fix in #168 would it be possible to cut a new release?

### CODE REVIEW

**Comment by rjmcneill** [comment]
@jhorwit2 thanks for merging my previous PR, would we be able to cut a patch version release for the repo now?

**Comment by anthonyhastings** [comment]
@jhorwit2 any idea when this will land? I'm eagerly waiting on this to reinforce my failure logic on a production application.

**Comment by jhorwit2** [comment]
@anthonyhastings @rjmcneill whoops i missed this PR. I released this earlier today actually so closing this.

**Comment by anthonyhastings** [comment]
Thanks very much @jhorwit2 !

**Comment by rjmcneill** [comment]
@jhorwit2 No worries at all, thanks for the release!

**Pull request closed without merging**
