### PR TITLE
Cut new release for v3.0.0

### PR DESCRIPTION
**Pull request by alistairjcbrown**
With the changes merged from PRs #162, #163 and #164, can we release a new version of the library?

### CODE REVIEW

**Comment by alistairjcbrown** [comment]
@jhorwit2 Awesome, thanks for merging this - would you be able to push a 3.0.0 build to npm?

**Comment by letsgojuno** [comment]
Nice work here 👍  Will v3 be getting published to the npm registry?

**Comment by jhorwit2** [comment]
@alistairjcbrown Sorry, I started on this yesterday (my npm got hosed when i did a back restore on my new laptop) then got sidetracked. I'll get to this later this evening.

**Comment by jhorwit2** [comment]
@alistairjcbrown published!

**Comment by alistairjcbrown** [comment]
@jhorwit2 Awesome, thanks!

**Pull request merged**
