### PR TITLE
debounce identical network requests

### LINKED ISSUE #52: Optimize Implore Requests
We should add two optimization efforts within implore. We should allow the ability to prevent duplicate route calls when the first once is still not finished. 

For example, lets say we request route A with `/path/id` then before the requests finishes we make the same request. We should ignore the second request since it's duplicate. 

We should also add an option to do the opposite. If we get the same request before the first one finishes, we should close the first one and open the second one.

### PR DESCRIPTION
**Pull request by mako-taco**
When multiple requests look identical, hash em
Fixes #52

### CODE REVIEW

**Comment by jhorwit2** [comment]
This solution isn't finished IMO. It appears that you are taking the approach that you should ignore duplicate requests and let the first one succeed before finishing. You also only call the promise once which I thought you wanted to avoid?

**Comment by jhorwit2** [comment]
If we are going to do this with implore, then we need to also add support to allow the first request to close & the second request to open. I think in that case, the first callback should be called w/ some status code & the second one called as normal.

**Comment by mako-taco** [comment]
We don't get the callbacks because we're doing this with promises.  As for the requests, it doesnt matter which one goes through.  They are identical.  canceling one and calling another should have exactly the same effect (since its GET or HEAD only)

**Comment by jhorwit2** [comment]
We could go back to promises?

**Comment by jhorwit2** [comment]
I would prefer that we give the option to use the latest request and stop the first xhr also.

**Comment by mako-taco** [comment]
I want to expose the `abort` method of the underlying XHR so users have higher control over requests

**Comment by mako-taco** [comment]
Going to try to rework implore a bit by extending `Promise` and providing it with some extra functionality.

**Pull request closed without merging**
